import { lookupUserByRssToken } from '../../../../src/rss-token';

// GET /api/quick-podcast/feed/:token.xml
// Public feed endpoint — the token in the URL is the only auth. Anyone with
// the URL can subscribe in Apple Podcasts etc. `itunes:block=yes` tells
// Apple's directory NOT to index this feed — non-negotiable privacy guard.
export async function onRequest(context: any) {
  if (context.request.method !== 'GET') return new Response('Not found', { status: 404 });
  const rawToken = String(context.params.token || '').replace(/\.xml$/i, '');
  if (!rawToken || rawToken.length < 16) return new Response('Not found', { status: 404 });

  const user = await lookupUserByRssToken(context.env.submoacontent_db, rawToken);
  if (!user) return new Response('Not found', { status: 404 });

  const accountId = user.account_id || 'makerfrontier';
  const episodes = await context.env.submoacontent_db.prepare(`
    SELECT e.id, e.topic, e.summary, e.audio_duration_seconds, e.created_at, e.audio_r2_key
    FROM podcast_episodes e
    JOIN podcasts p ON e.podcast_id = p.id
    WHERE e.account_id = ?
      AND e.status = 'audio_ready'
      AND e.source = 'quick'
      AND e.audio_r2_key IS NOT NULL
    ORDER BY e.created_at DESC
    LIMIT 100
  `).bind(accountId).all();

  const base = new URL(context.request.url).origin;
  const feedUrl = new URL(context.request.url).toString();
  const feedTitle = `Quick Podcast — ${user.name || 'Personal Feed'}`;
  const feedDescription = 'On-demand topic podcasts generated by SubMoa Quick Podcast. Private feed.';

  const items = ((episodes.results || []) as any[]).map(e => {
    const audioUrl = `${base}/api/quick-podcast/${e.id}/audio`;
    const pubDate = new Date((e.created_at || 0) * 1000).toUTCString();
    const duration = e.audio_duration_seconds || 600;
    const guid = `quickpodcast-${e.id}`;
    const description = e.summary || e.topic || '';
    return `
    <item>
      <title>${escapeXml(e.topic || 'Untitled')}</title>
      <description>${escapeXml(description)}</description>
      <pubDate>${pubDate}</pubDate>
      <guid isPermaLink="false">${guid}</guid>
      <enclosure url="${escapeXml(audioUrl)}" length="0" type="audio/mpeg"/>
      <itunes:duration>${formatDuration(duration)}</itunes:duration>
      <itunes:summary>${escapeXml(description)}</itunes:summary>
      <itunes:explicit>no</itunes:explicit>
    </item>`;
  }).join('');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
     xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
     xmlns:atom="http://www.w3.org/2005/Atom"
     xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>${escapeXml(feedTitle)}</title>
    <description>${escapeXml(feedDescription)}</description>
    <link>${base}/listen</link>
    <language>en-us</language>
    <itunes:author>SubMoa Quick Podcast</itunes:author>
    <itunes:summary>${escapeXml(feedDescription)}</itunes:summary>
    <itunes:owner>
      <itunes:name>${escapeXml(user.name || 'Quick Podcast user')}</itunes:name>
      <itunes:email>${escapeXml(user.email || 'noreply@submoacontent.com')}</itunes:email>
    </itunes:owner>
    <itunes:explicit>no</itunes:explicit>
    <itunes:category text="Technology"/>
    <itunes:block>yes</itunes:block>
    <itunes:type>episodic</itunes:type>
    <atom:link href="${escapeXml(feedUrl)}" rel="self" type="application/rss+xml"/>
    ${items}
  </channel>
</rss>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
    },
  });
}

function escapeXml(s: string): string {
  return (s ?? '').replace(/[<>&"']/g, c => ({
    '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;',
  }[c] ?? c));
}

function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  return h > 0
    ? `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
    : `${m}:${String(s).padStart(2, '0')}`;
}
