// src/pages/PlannerBuilding.jsx
// Intermediate page shown while the itinerary plan is being generated by the
// queue consumer. Polls /api/planner/:id/status every 3 seconds. Redirects
// to /planner/:id on success, shows an error state with retry on failure.

import { useEffect, useState } from 'react'
import './Dashboard.css'

const CheckSVG = () => (
  <svg width="10" height="8" viewBox="0 0 10 8" fill="none">
    <path d="M1 4l3 3 5-6" stroke="#000" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
)

function statusToStep(status) {
  if (status === 'plan_ready') return 3
  if (status === 'generating') return 1
  return 0
}

function Tracker({ stepIndex }) {
  const steps = ['Submitted', 'Building Plan', 'Plan Ready']
  return (
    <div className="db-pipeline" style={{ maxWidth: 520, margin: '0 auto 28px' }}>
      {steps.map((label, i) => {
        const isDone = stepIndex > i
        const isActive = stepIndex === i
        return (
          <div key={label} style={{ display: 'contents' }}>
            <div className="db-step">
              <div className={`db-step-dot${isDone ? ' db-done' : isActive ? ' db-active' : ''}`}>
                {isDone && <CheckSVG />}
              </div>
              <div className={`db-step-label${isActive ? ' db-active' : ''}`}>{label}</div>
            </div>
            {i < steps.length - 1 && (
              <div className={`db-step-line${isDone ? ' db-done' : ''}`} />
            )}
          </div>
        )
      })}
    </div>
  )
}

export default function PlannerBuilding({ navigate, id }) {
  const [status, setStatus] = useState('generating')
  const [error, setError] = useState('')
  const [retrying, setRetrying] = useState(false)

  useEffect(() => {
    if (!id) return
    let stopped = false

    async function poll() {
      try {
        const res = await fetch(`/api/planner/${id}/status`, { credentials: 'include' })
        const data = await res.json()
        if (!res.ok) throw new Error(data?.error || `HTTP ${res.status}`)
        if (stopped) return
        setStatus(data.status)
        if (data.status === 'plan_ready' || data.status === 'draft') {
          navigate(`/planner/${id}`)
        }
      } catch (e) {
        if (!stopped) setError(e.message)
      }
    }

    poll()
    const interval = setInterval(poll, 3000)
    return () => { stopped = true; clearInterval(interval) }
  }, [id, navigate])

  const retry = async () => {
    setRetrying(true)
    setError('')
    try {
      const res = await fetch(`/api/planner/${id}/retry`, {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data?.error || `HTTP ${res.status}`)
      setStatus('generating')
    } catch (e) {
      setError(e.message)
    } finally {
      setRetrying(false)
    }
  }

  const isFailed = status === 'generation_failed'
  const stepIndex = statusToStep(status)

  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh', padding: '80px 20px 120px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto', textAlign: 'center' }}>
        <div style={{ fontFamily: 'var(--font-ui)', fontSize: 10, fontWeight: 600, letterSpacing: '0.3em', color: 'var(--amber)', textTransform: 'uppercase', marginBottom: 14 }}>◎ Planner</div>

        <Tracker stepIndex={isFailed ? 0 : stepIndex} />

        {isFailed ? (
          <>
            <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(24px, 4vw, 36px)', color: 'var(--error)', marginBottom: 10 }}>
              Plan generation failed.
            </h1>
            <div style={{ fontFamily: 'var(--font-ui)', fontSize: 14, color: 'var(--text-mid)', marginBottom: 28 }}>
              Something went wrong while building your itinerary.
            </div>
            <div style={{ display: 'flex', justifyContent: 'center', gap: 10, flexWrap: 'wrap' }}>
              <button onClick={retry} disabled={retrying} style={btnSolid}>
                {retrying ? 'Retrying…' : 'Try Again'}
              </button>
              <a href="/dashboard" style={btnGhost}>Back to Dashboard</a>
            </div>
          </>
        ) : (
          <>
            <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(28px, 4.5vw, 42px)', color: 'var(--text)', marginBottom: 10 }}>
              Your plan is being built.
            </h1>
            <div style={{ fontFamily: 'var(--font-ui)', fontSize: 15, color: 'var(--text-mid)', marginBottom: 32 }}>
              We'll have your itinerary ready shortly.
            </div>
            <div style={{ display: 'flex', justifyContent: 'center', gap: 10, flexWrap: 'wrap' }}>
              <a href="/dashboard" style={btnGhost}>Back to Dashboard</a>
              <a href="/planner" style={btnSolid}>Build Another Plan</a>
            </div>
          </>
        )}

        {error && !isFailed && (
          <div style={{ marginTop: 20, fontSize: 12, color: 'var(--text-light)' }}>
            Last poll: {error}
          </div>
        )}
      </div>
    </div>
  )
}

const btnSolid = {
  padding: '10px 22px',
  fontSize: 14,
  fontWeight: 600,
  fontFamily: 'var(--font-ui)',
  background: 'var(--green)',
  color: '#fff',
  border: 'none',
  borderRadius: 7,
  cursor: 'pointer',
  textDecoration: 'none',
  display: 'inline-block',
}

const btnGhost = {
  padding: '10px 22px',
  fontSize: 14,
  fontWeight: 600,
  fontFamily: 'var(--font-ui)',
  background: 'transparent',
  color: 'var(--text-mid)',
  border: '1px solid var(--border)',
  borderRadius: 7,
  cursor: 'pointer',
  textDecoration: 'none',
  display: 'inline-block',
}
